# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ccf11f3081f48e0f22c760402c6939c1e8c29effa47d91136920b0b86a7cd670bf1db7e8e95f86da3f2b6eecf2c723de9fb3c5ae3e55b3cb601901a88662b32

test:
  secret_key_base: f89678ee04b4e84788547b7b682d2717804b43cd69d2b7123554e6e4a28d99b5828d3bad1c2f619f0b0d045e140bdc83da3daea049767966e2bcb3c41bba9f82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
